name: Tests
on: push
jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Install Truffle
        run: yarn global add truffle
      - name: Generate a mnemonic
        run: yarn add bip39 && node -e 'console.log(require("bip39").generateMnemonic())' > .mnemonic
      - name: Run tests
        run: yarn test

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test:unit
